### PR TITLE
Migrate to Edition 2021

### PR DESCRIPTION
**Pull request by futursolo**
This pull request migrates to edition 2021.

Since wasm-bindgen requires 1.56, there is no benefit to keep crates at edition 2018.
Upgrading the crates to edition 2021 will enable the rust-version field which suppresses clippy for lints not available in MSRV.

I have calculated the MSRV with `cargo-msrv`, which is 1.64.

### CODE REVIEW

**Comment by futursolo** [comment]
Tests are failing as Trunk released a new version 10 minutes ago.

**Comment by hamza1311** [comment]
Can you please also update the changelog?

Also, I believe this should be a minor version, not patch, when releasing, right?

**Comment by futursolo** [comment]
> Can you please also update the changelog?

This is done. I think we should have a PR template so people don't forget about this.

> Also, I believe this should be a minor version, not patch, when releasing, right?

I believe so as this pull request now requires 1.64 for all crates where as in the past only some crates require 1.64.

**Comment by hamza1311** [comment]
> This is done. Should we add a PR template so future contributors don't forget about this?

Good idea!

I also updated the CI so it runs against MSRV (and nightly) too. Will merge this once CI is green

**Pull request merged**
