### PR TITLE
Cargo lock update

### PR DESCRIPTION
**Pull request by langyo**
cc #411

### CODE REVIEW

**Review by futursolo — COMMENTED** [review]
Could you please add `wasm-bindgen = "0.2.88"` to `crates/history/Cargo.toml`?

`Cargo.lock` in gloo is not honoured if gloo-history is being referenced as a dependency in a different workspace.

**Comment by langyo** [comment]
> Could you please add `wasm-bindgen = "0.2.88"` to `crates/history/Cargo.toml`?
> 
> `Cargo.lock` in gloo is not honoured if gloo-history is being referenced as a dependency in a different workspace.

Done.

**Comment by futursolo** [comment]
@hamza1311 Do you want to raise MSRV to 1.67?

I am fine with raising MSRV, but this is technically a breaking change, so we might have to raise the minor version.
wasm-bindgen itself does not raise the MSRV, so we can avoid increasing MSRV if we do not update all dependencies.

**Comment by hamza1311** [comment]
I'm fine with bumping the MSRV but it has to be for a good reason. What dependency needs to be bumped here?

If that will push usage of wasm-bindgen `>=0.2.88`, that's a good enough reason for me

**Comment by futursolo** [comment]
> What dependency needs to be bumped here?

Raise of MSRV is side effect of `cargo update`. `wasm-bindgen` does not raise MSRV.
We only need `wasm-bindgen >= 0.2.88`.

**Comment by langyo** [comment]
> I'm fine with bumping the MSRV but it has to be for a good reason. What dependency needs to be bumped here?
> 
> If that will push usage of wasm-bindgen `>=0.2.88`, that's a good enough reason for me

I've checked the CI log and found it finally caused by `gloo-worker-macros`. It depends the new version of `proc-macro-crate`.

**Comment by hamza1311** [comment]
Can you just update the dependencies using `cargo +nightly update -Zmsrv-policy`? That _should_ update the dependencies to MSRV compatible versions. I don't want to raise the MSRV just for a proc-macro dependency

**Comment by langyo** [comment]
> Can you just update the dependencies using `cargo +nightly update -Zmsrv-policy`? That _should_ update the dependencies to MSRV compatible versions. I don't want to raise the MSRV just for a proc-macro dependency, primarily because it forces the same for downstream crates.

Ummm...Sure

I'll try it later

**Comment by hamza1311** [comment]
I created #424 which bumps dependencies without raising MSRV

**Comment by langyo** [comment]
> I created #424 which bumps dependencies without raising MSRV

Okay..

By the way, you reminded me that I'll be reworking the general PR on the `yew` later to change the MSRV part.

**Review by futursolo — COMMENTED** [review]
@langyo

Could you please remove the MSRV changes and rebase `Cargo.lock` from master?

**Comment by langyo** [comment]
> @langyo
> 
> Could you please remove the MSRV changes and rebase `Cargo.lock` from master?

Oh...I was made a mistake..I rolled back too far...

But since @hamza1311 has completed this part of the work..In fact, this PR is a duplicate, and it should not be a problem to turn it off.

Next I'll see how to remove the compilation macro of wasi...

**Pull request closed without merging**
