### PR TITLE
Adding in note about how to handle Futures / Streams

### PR DESCRIPTION
**Pull request by Pauan**
See #27

### CODE REVIEW

**Comment by fitzgen** [comment]
Oh also: since `Future` and `Stream` are both defined in the `futures` crate, does it make sense to have separate submodules for them? Should they both be inside the crate's `futures` submodule?

**Comment by fitzgen** [comment]
Oh also: we should mention that the `futures` usage should be behind a `"futures"` cargo feature!

**Comment by fitzgen** [comment]
Also also: should the top-level `gloo` crate have a `futures` feature that enables all of the sub-crates' `futures` features?

I'm leaning towards "yes" for convenience, but I'm also interested in what others think.

**Comment by Pauan** [comment]
> Oh also: since Future and Stream are both defined in the futures crate, does it make sense to have separate submodules for them? Should they both be inside the crate's futures submodule?

The `futures` (plural) crate has separate `future` and `stream` (singular) submodules, so I just went with that.

I don't have strong opinions one way or the other, but I do like segregating by types, and it also paves the way to other types (like `signal`).

> Also also: should the top-level gloo crate have a futures feature that enables all of the sub-crates' futures features?

That sounds good to me.

**Comment by Pauan** [comment]
I added a note about high-level and mid-level APIs.

I think we need to have consensus on what the future/stream cargo feature should be called before I make a note about it.

**Pull request merged**
