### PR TITLE
[RFC] WebGL

### PR DESCRIPTION
**Pull request by asny**
Continuing from issue [#5](https://github.com/rustwasm/gloo/issues/5)

### CODE REVIEW

**Comment by derekdreery** [comment]
Awesome work. I'm not really placed to offer an opinion on the proposal as a whole, but I have a couple of questions:

 1. If there are some combinations of parameters that are not allowed, can we create types that represent the allowed subset using sum and product types (enums and structs)?
 2. Do we want to support WebGL rather than WebGPU, since people using wasm are going to have an up-to-date browser, and WebGPU is designed to replace WebGL?

**Comment by Pauan** [comment]
@derekdreery I think the problem is that WebGPU isn't even remotely close to ready (it's not standardized yet, the design is still in flux, it currently [only runs on Mac OS X Chrome Canary](https://doc.babylonjs.com/extensions/webgpu), *and* you have to enable an experimental flag, *and* it's missing a ton of features, *and* it's going to be buggy).

But yeah, in the long term we'll want to replace WebGL with WebGPU.

**Comment by hamza1311** [comment]
Hey @ansy, can you create an issue for this RFC. See #136 for details

**Comment by asny** [comment]
Hi @hamza1311 , it is already there #5

**Comment by hamza1311** [comment]
> Hi @hamza1311 , it is already there #5 

You mentioned that it's a continuation. I haven't read *both* so can you confirm that it's all the information is there?

**Comment by hamza1311** [comment]
Just read it, seems like the issue does have the information. Closing this in favor of #5

**Pull request closed without merging**
