### PR TITLE
Execute websocket test assertions

### PR DESCRIPTION
**Pull request by richardpringle**
The assertions were not doing anthing before, they were only queued to
run

Proof that they are running now: #393

Fixes: #368

### CODE REVIEW

**Comment by richardpringle** [comment]
Partially solves #368 

@carlsverre, I just realized that I basically stole your code (even though I looked at it afterwards). If you care about the contribution credit, this should be your PR

**Comment by carlsverre** [comment]
All good! Don't care about contribution credit in this case, just that it's fixed. Thanks for working on it!

I guess leave eventsource fixes for a future pr?

**Comment by richardpringle** [comment]
I could not for the life of me get the tests in `io_util` to run locally, so not sure about the change there.

**Review by hamza1311 — APPROVED** [review]
Thanks!

**Pull request merged**
