### PR TITLE
First draft of RFC for websockets API.

### PR DESCRIPTION
**Pull request by derekdreery**
This is a first draft of a websocket API. I don't think it's ready to merge yet, but I wanted to start the conversation.

[rendered](https://github.com/derekdreery/gloo/edit/ws-rfc/rfcs/000-websocket-api.md?pr=%2Frustwasm%2Fgloo%2Fpull%2F113)

### CODE REVIEW

**Comment by derekdreery** [comment]
Can someone explain to me how to link the rendered document without it being tied to a specific blob?

**Comment by derekdreery** [comment]
ping

**Comment by Lemmih** [comment]
I would like to assist. The draft of the API looks complete enough for an experimental implementation. What would be the best next steps for this?

**Comment by hamza1311** [comment]
I just saw this. I would suggest using an API based on channels/streams as that's consistent with other websocket crates and, imo, is more "rust-y". See [this implementation of such an API in `reqwasm`](https://github.com/hamza1311/reqwasm/blob/master/src/websocket.rs) as an example.

**Comment by Lemmih** [comment]
The `futures` API from the proposal is consistent with the API from `reqwasm`, right?

**Comment by hamza1311** [comment]
Seems that way. I somehow missed the figured part. This API looks good.

**Review by hamza1311 — CHANGES_REQUESTED** [review]
I left a few comments. Generally, it looks good.

**Comment by hamza1311** [comment]
Another thing: @derekdreery, can you create an issue for this RFC with the changes. See #136 for details

**Pull request closed without merging**
