### PR TITLE
Create a website

### LINKED ISSUE #135: Keep/host mdbook vs create a website
Gloo needs a web page. We have the following 2 options:
1. Keep the [current mdbook](https://github.com/rustwasm/gloo/tree/master/guide), bring it up to date and host it
2. Create a website like [Yew's](https://yew.rs)

I don't really see the downside of going with 2. We can even have a gloo-specific blog that way. Gloo isn't big enough that it needs a book. API docs exist on docs.rs, everything else can be on the website.

### PR DESCRIPTION
**Pull request by hamza1311**
[Preview URL](https://gloo-rs--site-preview-pb9mfx2j.web.app/)
Closes #135

### CODE REVIEW

**Comment by eggyal** [comment]
FYI just visited this preview using Safari on iPhone 7 (iOS 14.5.1) and in portrait orientation the main body text is only about 5em wide, which obviously isn't very legible.

**Comment by hamza1311** [comment]
@eggyal, I fixed that, please take a look again.

**Comment by eggyal** [comment]
Yep, much better!  Thanks

**Comment by hamza1311** [comment]
Nice. All I need is the permissions to add secrets so I can add the service account needed to deploy the site via CI

Re-pinging @alexcrichton for help (PS: I'm sorry for the pings, I want to get this done soon)

**Comment by hamza1311** [comment]
I'm going to go ahead and merge this. I suspect the CI failure is because of secret not being passed because of fork..

**Pull request merged**
