### PR TITLE
Update Cargo.lock (2)

### PR DESCRIPTION
**Pull request by hamza1311**
#423 but without raising MSRV

### CODE REVIEW

**Review by futursolo — COMMENTED** [review]
#423 also updates `crates/history/Cargo.toml` to include `wasm-bindgen = "0.2.88"`, so it will be respected when used as a dependency.

If you want to keep #423 to update wasm-bindgen, that’s fine with me as well.

**Comment by futursolo** [comment]
In addition, could you please wait until gloo-history removed the wasi compiler flags before releasing the next version?

See: https://github.com/rustwasm/gloo/pull/411#discussion_r1421379894

**Comment by langyo** [comment]
> In addition, could you please wait until gloo-history removed the wasi compiler flags before releasing the next version?
> 
> See: [#411 (comment)](https://github.com/rustwasm/gloo/pull/411#discussion_r1421379894)

If necessary, I'll removing additional WASI judgment tags when this PR has merged.

**Review by futursolo — APPROVED** [review]
Let’s merge this and address `Cargo.toml` in #423.

**Pull request merged**
